### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Xzjosh** [YaLTeR/SourcePauseTool#145]
i put in the spt things but a lot of the things don't work. All it does is pause the game

**Comment by InputEvelution** [comment]
Can you provide any more detail whatsoever about the specific issues that
you're dealing with?

**Comment by UncraftedName** [comment]
It's likely that you didn't remove any old versions of spt (unpack comes with at least 1). If you load the plugin it tells you the build date, just make sure it's up to date and remove any old versions if it isn't.

**Comment by Xzjosh** [comment]
InputEvelution a lot of the commands don't work and when I type Plugin_load spt, all it does is put a thing in my face when i die or reload

**Comment by InputEvelution** [comment]
You're definitely not using the latest version of SPT, which is heavily advised if you're reporting bugs. You should also give details about what specific commands don't work, as well as what game and build you're playing on.

**Comment by Xzjosh** [comment]
I'm definitely using the latest version. If you go to source runs 98% of the commands don't work. I am trying to use build 5135 for Portal

**Comment by UncraftedName** [comment]
Show a screenshot of the console output when you load spt.

**Comment by Xzjosh** [comment]
![testchmb_a_000001](https://user-images.githubusercontent.com/66355434/85686555-6978af80-b713-11ea-9d88-92fc6bed6f34.jpg)
![testchmb_a_000002](https://user-images.githubusercontent.com/66355434/85686586-6f6e9080-b713-11ea-898b-4f5ee0dd8bfd.jpg)

**Comment by InputEvelution** [comment]
For starters, you are certainly not using the latest version of SPT here - the version listed is "v0.6", which was released back in August 2014 - almost six years old. I don't know if you simply followed the directions to insert the newest version of the plugin incorrectly, but you need to download the most recent spt.dll from https://github.com/YaLTeR/SourcePauseTool/releases and replace the one in your game directory with that.

Secondly, the only command which is actually being listed as not working here is y_spt_additional_abh - a command which doesn't need to work in Portal anyway, since it already has ABH and this is mainly intended for games like Portal 2 and Half-Life Source that don't have this game mechanic. To enable features like autojump and disable features like the autopause you need to type in the developer console again - y_spt_pause 0 should disable autopause, and y_spt_autojump 1 should enable autojump. You can see a list of available commands by entering y_ or _y_, and entering any of them into the console on their own should tell you exactly what they are for and how to use them.

**Comment by Xzjosh** [comment]
I downloaded that, put it into my games directory, I am using Source unpack and their is nothing called spt or anything in the portal directory. It still comes up with version 06

**Comment by Xzjosh** [comment]
Never mind everyone. My friend played around with it and managed to figure it out. Thanks for everyones cooperation. I look for to TASing.
