### ISSUE TITLE
y_spt_autojump Only works in HL2 and no other games

### ISSUE THREAD

**Issue by PainTrainsInPainTown** [YaLTeR/SourcePauseTool#197]
y_spt_autojump will only work in HL2 and not in Portal 1 or Portal 2.

**Comment by SmileyAG** [comment]
Portal 2 SPT support been dropped, since a lot of ppls from P2 community been used fork of SAR: https://github.com/p2sr/SourceAutoRecord

It's possible that there is no pattern for the latest steampipe version of Portal, so you can downgrade `server.dll` by downloading the old depots to get the autojump working again, or ask someone who does reverse-engineering to update steam pattern for Portal in SPT.

Autojump in Portal of 5135 build (Source Unpack 2.4) should still works cuz pattern been found a years ago and that unpack cannot be affected from Steam updates.

**Comment by PainTrainsInPainTown** [comment]
Okay, thanks for helping!

**Comment by lipsanen** [comment]
yea the latest steam update basically broken everything for portal 1

**Comment by lambda1280** [comment]
Actually, not only _Portal_ series...

I tried to load "spt.dll" or "spt-2013.dll" into _Entropy Zero_
but it always said "`y_spt_autojump` has no effect."

**_HOW??????_**

**Comment by SmileyAG** [comment]
> Actually, not only _Portal_ series...
> 
> I tried to load "spt.dll" or "spt-2013.dll" into _Entropy Zero_ but it always said "`y_spt_autojump` has no effect."
> 
> **_HOW??????_**

Entropy Zero likely using a custom DLLs, which compiled on modified Source SDK base & different MSVC versionn, so that's so expected that pattern for autojump would be not found, cuz it requires additional support for modification.

I meant in SPT base for such things like autojump only a few exclusive mods mb have it, like DMoMM, like we don't care too much about support everything, so if u have knowledge of C++ and reverse-engineering, then u can find offsets and patterns for modification what you more like and make a pull request to repo.

**Comment by lipsanen** [comment]
p1 autojump should now work on all versions, closing this
