### ISSUE TITLE
autojump doesn't work in newest update of hl2

### ISSUE THREAD

**Issue by sSolle** [YaLTeR/SourcePauseTool#202]
it just don't

**Comment by SmileyAG** [comment]
I got changed pattern for hl2 steampipe in https://github.com/YaLTeR/SourcePauseTool/commit/f31e17ebc890ab2c7bc132c003d83543321d2979 commit, so that should works now.

Latest SPT with new autojump pattern can be downloaded via GitHub Actions: https://github.com/YaLTeR/SourcePauseTool/suites/5611153890/artifacts/182455444

**Comment by sSolle** [comment]
yep that works
