### ISSUE TITLE
Black Mesa Standalone not working

### ISSUE THREAD

**Issue by Draakoor** [YaLTeR/SourcePauseTool#25]
Hi there,

when I try loading the plugin, the game crashes without any errors.

**Comment by Traderain** [comment]
Check #11. You may be able to resolve it.

**Comment by bartico6** [comment]
Bumping issue, still doesn't work (any of the two appropriate versions provided in releases) - game closes without a single error. The file provided in issue #11 is dead (that is, the link points to a 404)

**Comment by YaLTeR** [comment]
Well, looks like I'll have to add support for that. Meanwhile, maybe you want the mod version of Black Mesa instead? It's much more speedrun-friendly and also SPT works on it.

**Comment by bartico6** [comment]
Oh I'm not in a hurry to use SPT, I merely wanted to mess around bunnyhopping but turns out standalone steam BM won't work. I'll just patiently wait for the support, no need to hurry though! :)

**Comment by YaLTeR** [comment]
Use the mod version, you'll have a more pleasing experience of messing
around with bunnyhopping. There's a hard cap in the steam version which is
easy to trigger even with autojump.

**Comment by Breakthrough** [comment]
Hey @YaLTeR;

Is there any way the hard cap can be removed/modified, as is done in Bunnymod XT?

Thanks, and great project!

**Comment by YaLTeR** [comment]
There is, I haven't done it yet because:
1) speedruns are done on the older version anyway (since they patched more stuff in this one)
2) if people were to speedrun the steam version they would probably run it with the cap

So yeah, no one really needed it.

**Comment by Breakthrough** [comment]
Ah, gotcha.  Was just wondering, because they added Surface Tension Uncut to the official Steam release (unsure if they do in speedruns of BM:S) which is a bit more faithful to the original, although I guess the mod version supports it as well (not to mention both mod/retail support On A Rail Uncut, which I highly recommend you give a shot if you haven't, it's a great addition).  I looked into some more specific things they patched in the changelogs, and can see why it's not really necessary to have BXT support BM Retail.

I'll give BXT a shot with the mod version, thanks for the reply!

**Comment by YaLTeR** [comment]
SPT, not BXT. BXT is for GoldSource games.

**Comment by Breakthrough** [comment]
Yes, my bad, I did mean SPT and not BXT.  (You figure the repo name would've reminded me :P)  Thanks for the correction, comment updated 👍   (will delete this one soon)

**Comment by YaLTeR** [comment]
Closing because #15 exists.
