### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by 0x2480** [YaLTeR/SourcePauseTool#66]
Would it be possible to support any of the 2007 versions of TF2?

**Comment by YaLTeR** [comment]
What functionality are you looking for? SPT is mainly a single-player plugin and I'm not sure that it would work in multiplayer properly.

**Comment by TERRAERROR** [comment]
Bare minimum is autojump because bhop works, If it wont work on it tho then ok..

**Comment by Jung504** [comment]
You can do this with sourcemods.   Check Allied modders.

**Comment by mikesmiffy128** [comment]
As someone who has dealt with L4D2 autojump on many past occasions I must disagree with that suggestion - you need clientside prediction for it not to lag unbearably. On the other hand if you're running a bhop server it's probably the only option since your players are probably not gonna be installing a plugin just to join. Or maybe you're not doing that and you want to cheat - in that case you won't be able to as SPT requires -insecure and so it won't let you connect to VAC servers.

Conclusion: meh I guess sourcemod would work
