### ISSUE TITLE
Portal 2 crashes when I am starting to jump with spt-p2.dll with y_spt_additional_jumpboost "1"

### ISSUE THREAD

**Issue by sFurrman** [YaLTeR/SourcePauseTool#90]

**Comment by Jukspa** [comment]
as far as I know, this is only intended to be used with black mesa source

**Comment by TheProJamer** [comment]
This feature is _not_ solely intended to be used with Black Mesa Source, it has been a feature for other Source games such as Half-Life Source and Portal 2 since I added the necessary code for it 2 years ago. I even uploaded two videos to my YouTube channel demonstrating the feature (https://www.youtube.com/watch?v=7dQ9w2QQgww and https://www.youtube.com/watch?v=ANpYm15IjSQ).

However, it has been a substantial period of time since Portal 2 patterns were added to SPT, and I would not be surprised if the updates since then have caused functionality to break. I cannot guarantee that I will be able to find the motivation to go to the effort of fixing the issue, especially as many Portal 2 runners have moved on from SPT altogether in favour of SAR, which uses the exact same code and should work with the latest update.

**Comment by CoolStuff08** [comment]
> This feature is _not_ solely intended to be used with Black Mesa Source, it has been a feature for other Source games such as Half-Life Source and Portal 2 since I added the necessary code for it 2 years ago. I even uploaded two videos to my YouTube channel demonstrating the feature (https://www.youtube.com/watch?v=7dQ9w2QQgww and https://www.youtube.com/watch?v=ANpYm15IjSQ).
> 
> However, it has been a substantial period of time since Portal 2 patterns were added to SPT, and I would not be surprised if the updates since then have caused functionality to break. I cannot guarantee that I will be able to find the motivation to go to the effort of fixing the issue, especially as many Portal 2 runners have moved on from SPT altogether in favour of SAR, which uses the exact same code and should work with the latest update.

where can you get SAR

**Comment by mlugg** [comment]
> > This feature is _not_ solely intended to be used with Black Mesa Source, it has been a feature for other Source games such as Half-Life Source and Portal 2 since I added the necessary code for it 2 years ago. I even uploaded two videos to my YouTube channel demonstrating the feature (https://www.youtube.com/watch?v=7dQ9w2QQgww and https://www.youtube.com/watch?v=ANpYm15IjSQ).
> > However, it has been a substantial period of time since Portal 2 patterns were added to SPT, and I would not be surprised if the updates since then have caused functionality to break. I cannot guarantee that I will be able to find the motivation to go to the effort of fixing the issue, especially as many Portal 2 runners have moved on from SPT altogether in favour of SAR, which uses the exact same code and should work with the latest update.
> 
> where can you get SAR

https://sar.portal2.sr/
